version: '3.8'
services:
  postgres:
    container_name: postgres15
    image: postgres:15.3-alpine
    restart: unless-stopped
#    restart: always
    ports:
      - '15432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      TZ: "Europe/Moscow"
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    networks:
      frontend:
        ipv4_address: 192.168.230.7

  php:
    container_name: php-fpm
#    build:
#      context: ./php-fpm
    build: ./docker/php-fpm
    restart: unless-stopped
    ports:
      - '9001:9000'
    volumes:
      - ./:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
#      - ./../src/:/var/www
    depends_on:
      - postgres
    environment:
#      - APP_ENV=${APP_ENV}
#      - APP_SECRET=${APP_SECRET}
#      - DATABASE_URL=${DATABASE_URL}
      TZ: "Europe/Moscow"
    networks:
      frontend:
        ipv4_address: 192.168.230.6

  nginx:
    container_name: nginx-upload
    build: ./docker/nginx
    restart: unless-stopped
    ports:
      - '8081:80'
    depends_on:
      - php
    volumes:
      - ./:/var/www/symfony
      - ./logs/nginx/:/var/log/nginx:cached
    environment:
      TZ: "Europe/Moscow"
    networks:
      frontend:
        ipv4_address: 192.168.230.5

networks:
  frontend:
    ipam:
      config:
        - subnet: 192.168.230.0/24
